### ISSUE TITLE
Don't we need an Event for the function ?

### ISSUE THREAD

**Issue by chapimenge3** [jojo786/Sample-Python-Telegram-Bot-AWS-Serverless#1]
Don't we need some kind of event like this 

```yaml
Events:
        Api:
          Type: Api
          Properties:
            Path: /bot
            Method: post
```

and set the webhook to that event ?

https://api.telegram.org/botTOKEN/url=API-GATEWAY-URL

Just to give a full working example.
